// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:quan_li_chi_tieu_2/core/cash_flow_data.dart';
import 'package:quan_li_chi_tieu_2/core/category_type.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CashFlowDataAdapter());
    registerAdapter(CategoryTypeAdapter());
  }
}
